"""Initial schema

Revision ID: d1f7f4b25fe9
Revises: 
Create Date: 2026-09-06 17:00:34.889223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1f7f4b25fe9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.create_table('facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facilities_city', 'facilities', ['city'], unique=False)
    op.create_index('ix_facilities_state', 'facilities', ['state'], unique=False)
    op.create_index('ix_facilities_type', 'facilities', ['type'], unique=False)
    op.create_table('osm_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('osm_type', sa.String(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_osm_features_type', 'osm_features', ['feature_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('hotspots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ml_type', sa.String(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('ml_explanation', sa.String(), nullable=True),
    sa.Column('land_cover_class', sa.Integer(), nullable=True),
    sa.Column('land_cover_name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotspots_facility_id', 'hotspots', ['facility_id'], unique=False)
    op.create_index('ix_hotspots_ml_type', 'hotspots', ['ml_type'], unique=False)
    op.create_index('ix_hotspots_severity', 'hotspots', ['severity'], unique=False)
    op.create_index('ix_hotspots_state', 'hotspots', ['state'], unique=False)
    op.create_index('ix_hotspots_timestamp', 'hotspots', ['timestamp'], unique=False)
    op.create_index('ix_hotspots_type', 'hotspots', ['type'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hotspot_id', sa.String(), nullable=True),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_facility_id', 'alerts', ['facility_id'], unique=False)
    op.create_index('ix_alerts_hotspot_id', 'alerts', ['hotspot_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_timestamp', 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotspots')
    op.drop_table('osm_features')
    op.drop_table('facilities')
    # ### end Alembic commands ###
